get http://localhost:4000/users

###
 get http://localhost:4000/users/2

###
post http://localhost:4000/user
Content-Type: application/json

{
    "id":3,
    "username":"janaki"
}

###
get http://localhost:4000/bikes




###
put http://localhost:4000/user
Content-Type: application/json

{
    "id":1,
    "username":"Lokesh Gandham"
}
###
delete http://localhost:4000/user
